### PR TITLE
Pass basic connection information to backend

### LINKED ISSUE #232: Expose connection state to the backend
Adding something similar to ConnectionState from go-smtp (https://github.com/emersion/go-smtp/issues/15) would be useful. For example, then [maddy](https://github.com/emersion/maddy) will be able to log IP addresses of clients on failed authentication, which is required for fail2ban to work.

_I guess I can implement it, just creating issue so I will not forget about it (I already did it like, 2 times)_

### PR DESCRIPTION
**Pull request by foxcpp**
Similar to go-smtp's ConnectionState. For https://github.com/emersion/maddy/issues/29. Breaking change.

Closes #232.

### CODE REVIEW

File: conn.go [hunk 1]
```diff
@@ -135,6 +136,15 @@ func newMultiFlusher(flushers ...flusher) flusher {
 	return &multiFlusher{flushers}
 }
 
+// Underlying connection state information.
+type ConnInfo struct {
+	RemoteAddr net.Addr
+	LocalAddr  net.Addr
+
+	// Not populated if connection is not using TLS.
+	TLS tls.ConnectionState
```
Comment (emersion) [inline conn.go]: Should be a pointer?

File: conn.go [hunk 2]
```diff
@@ -135,6 +136,15 @@ func newMultiFlusher(flushers ...flusher) flusher {
 	return &multiFlusher{flushers}
 }
 
+// Underlying connection state information.
+type ConnInfo struct {
```
Comment (emersion) [inline conn.go]: Should be named `ConnectionState`

Comment (foxcpp) [reply conn.go]: There is already ConnState so I decided to pick a different name to prevent possible confusion. Should I still rename it to ConnectionState?

Comment (emersion) [reply conn.go]: Gah, okay, makes sense

File: conn.go (hunk 1 above)
Comment (foxcpp) [reply conn.go]: Changed to pointer in ed492a9.

**Comment by foxcpp** [comment]
CI broke :(

**Comment by emersion** [comment]
Yeah. On the master branch I switched to sr.ht, but I guess this branch doesn't have the `.build.yml` file. Can you rebase?

**Comment by foxcpp** [comment]
Rebased.

**Comment by emersion** [comment]
Thanks!
