### PR TITLE
Explicit separation for quoted strings and atoms

### LINKED ISSUE #242: Quote everything that needs to be quoted
We try to be smart with quoting and it doesn't work well.

We need to read the ABNF and make sure atoms aren't quoted and quoted strings are correctly quoted.

### PR DESCRIPTION
**Pull request by foxcpp**
Opening PR early to make sure you can peek at it and leave feedback as I mess around with it.
Also to make sure I will not forget to run tests after each commit :p. 

Closes #242.

### CODE REVIEW

File: write.go [hunk 1]
```diff
@@ -175,7 +175,7 @@ func (w *Writer) writeField(field interface{}) error {
 		return w.writeAstring(field)
 	case Quoted:
 		return w.writeQuoted(string(field))
-	case Atom:
+	case RawString:
 		return w.writeAtom(string(field))
```
Comment (emersion) [inline write.go]: This needs to be renamed as well

Comment (foxcpp) [reply write.go]: I removed this function in 36e9bb1.

File: client/cmd_auth_test.go [hunk 2]
```diff
@@ -25,8 +25,8 @@ func TestClient_Select(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "SELECT INBOX" {
-		t.Fatalf("client sent command %v, want SELECT INBOX", cmd)
+	if cmd != "SELECT \"INBOX\"" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
select          = "SELECT" SP mailbox
mailbox         = "INBOX" / astring
```

File: client/cmd_auth_test.go [hunk 3]
```diff
@@ -74,8 +74,8 @@ func TestClient_Select_ReadOnly(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "EXAMINE INBOX" {
-		t.Fatalf("client sent command %v, want EXAMINE INBOX", cmd)
+	if cmd != "EXAMINE \"INBOX\"" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
examine         = "EXAMINE" SP mailbox
mailbox         = "INBOX" / astring
```

File: client/cmd_auth_test.go [hunk 4]
```diff
@@ -170,8 +170,8 @@ func TestClient_Subscribe(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "SUBSCRIBE Mailbox" {
-		t.Fatalf("client sent command %v, want %v", cmd, "SUBSCRIBE Mailbox")
+	if cmd != "SUBSCRIBE \"Mailbox\"" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
subscribe       = "SUBSCRIBE" SP mailbox
mailbox         = "INBOX" / astring
```

File: client/cmd_auth_test.go [hunk 5]
```diff
@@ -193,8 +193,8 @@ func TestClient_Unsubscribe(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "UNSUBSCRIBE Mailbox" {
-		t.Fatalf("client sent command %v, want %v", cmd, "UNSUBSCRIBE Mailbox")
+	if cmd != "UNSUBSCRIBE \"Mailbox\"" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
unsubscribe       = "UNSUBSCRIBE" SP mailbox
mailbox         = "INBOX" / astring
```

File: client/cmd_auth_test.go [hunk 6]
```diff
@@ -301,8 +301,8 @@ func TestClient_Status(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "STATUS INBOX (MESSAGES RECENT)" {
-		t.Fatalf("client sent command %v, want %v", cmd, "STATUS INBOX (MESSAGES RECENT)")
+	if cmd != "STATUS \"INBOX\" (MESSAGES RECENT)" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
status          = "STATUS" SP mailbox SP
                  "(" status-att *(SP status-att) ")"
mailbox         = "INBOX" / astring
```

File: client/cmd_auth_test.go [hunk 7]
```diff
@@ -336,8 +336,8 @@ func TestClient_Append(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "APPEND INBOX (\\Seen \\Draft) \"10-Nov-2009 23:00:00 +0000\" {30}" {
-		t.Fatalf("client sent command %v, want %v", cmd, "APPEND INBOX (\\Seen \\Draft) \"10-Nov-2009 23:00:00 +0000\" {30}")
+	if cmd != "APPEND \"INBOX\" (\\Seen \\Draft) \"10-Nov-2009 23:00:00 +0000\" {30}" {
```
Comment (foxcpp) [inline client/cmd_auth_test.go]:
```
append          = "APPEND" SP mailbox [SP flag-list] [SP date-time] SP
                  literal
mailbox         = "INBOX" / astring
```

File: client/cmd_noauth_test.go [hunk 8]
```diff
@@ -121,7 +121,7 @@ func TestClient_Login_Success(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "LOGIN username password" {
+	if cmd != "LOGIN \"username\" \"password\"" {
```
Comment (foxcpp) [inline client/cmd_noauth_test.go]:
```
login           = "LOGIN" SP userid SP password
userid          = astring
password        = astring
```

File: client/cmd_noauth_test.go [hunk 9]
```diff
@@ -145,7 +145,7 @@ func TestClient_Login_Error(t *testing.T) {
...
```
Comment (foxcpp) [inline client/cmd_noauth_test.go]:
```
login           = "LOGIN" SP userid SP password
userid          = astring
password        = astring
```

File: client/cmd_noauth_test.go [hunk 10]
```diff
@@ -169,8 +169,8 @@ func TestClient_Login_State_Allowed(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "LOGIN username password" {
-		t.Fatalf("client sent command %v, want LOGIN username password", cmd)
+	if cmd != "LOGIN \"username\" \"password\"" {
```
Comment (foxcpp) [inline client/cmd_noauth_test.go]:
```
login           = "LOGIN" SP userid SP password
userid          = astring
password        = astring
```

File: client/cmd_selected_test.go [hunk 11]
```diff
@@ -125,7 +125,7 @@ func TestClient_Search(t *testing.T) {
 		done <- err
 	}()
 
-	wantCmd := `SEARCH CHARSET UTF-8 SINCE "1-Feb-1994" FROM Smith DELETED NOT (TO Pauline)`
+	wantCmd := `SEARCH CHARSET "UTF-8" SINCE "1-Feb-1994" FROM "Smith" DELETED NOT (TO "Pauline")`
```
Comment (foxcpp) [inline client/cmd_selected_test.go]:
```
search          = "SEARCH" [SP "CHARSET" SP astring] 1*(SP search-key)
                    ; CHARSET argument to MUST be registered with IANA
```

File: client/cmd_selected_test.go [hunk 12]
```diff
@@ -162,7 +162,7 @@ func TestClient_Search_Uid(t *testing.T) {
 		done <- err
 	}()
 
-	wantCmd := "UID SEARCH CHARSET UTF-8 UNDELETED"
+	wantCmd := "UID SEARCH CHARSET \"UTF-8\" UNDELETED"
```
Comment (foxcpp) [inline client/cmd_selected_test.go]:
```
search          = "SEARCH" [SP "CHARSET" SP astring] 1*(SP search-key)
                    ; CHARSET argument to MUST be registered with IANA
```

File: client/cmd_selected_test.go [hunk 13]
```diff
@@ -474,8 +474,8 @@ func TestClient_Copy(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "COPY 2:4 Sent" {
-		t.Fatalf("client sent command %v, want %v", cmd, "COPY 2:4 Sent")
+	if cmd != "COPY 2:4 \"Sent\"" {
```
Comment (foxcpp) [inline client/cmd_selected_test.go]:
```
copy            = "COPY" SP sequence-set SP mailbox
```

File: client/cmd_selected_test.go [hunk 14]
```diff
@@ -499,8 +499,8 @@ func TestClient_Copy_Uid(t *testing.T) {
 	}()
 
 	tag, cmd := s.ScanCmd()
-	if cmd != "UID COPY 78:102 Drafts" {
-		t.Fatalf("client sent command %v, want %v", cmd, "UID COPY 78:102 Drafts")
+	if cmd != "UID COPY 78:102 \"Drafts\"" {
```
Comment (foxcpp) [inline client/cmd_selected_test.go]:
```
uid             = "UID" SP (copy / fetch / search / store)
                    ; Unique identifiers used instead of message
                    ; sequence numbers
copy            = "COPY" SP sequence-set SP mailbox
```

File: command_test.go [hunk 15]
```diff
@@ -48,8 +48,8 @@ func TestCommand_WriteTo_WithArgs(t *testing.T) {
 	if err := cmd.WriteTo(w); err != nil {
 		t.Fatal(err)
 	}
-	if b.String() != "A002 LOGIN username password\r\n" {
-		t.Fatal("Not the expected command")
+	if b.String() != "A002 LOGIN \"username\" \"password\"\r\n" {
```
Comment (foxcpp) [inline command_test.go]:
```
login           = "LOGIN" SP userid SP password
userid          = astring
password        = astring
```

File: message_test.go [hunk 16]
```diff
@@ -66,11 +66,11 @@ var messageTests = []struct {
 			itemsOrder:    []FetchItem{FetchEnvelope, FetchBody, FetchFlags, FetchRFC822Size, FetchUid},
 		},
 		fields: []interface{}{
-			"ENVELOPE", envelopeTests[0].fields,
-			"BODY", bodyStructureTests[0].fields,
-			"FLAGS", []interface{}{RawString(SeenFlag), RawString(AnsweredFlag)},
-			"RFC822.SIZE", "4242",
-			"UID", "2424",
+			RawString("ENVELOPE"), envelopeTests[0].fields,
```
Comment (foxcpp) [inline message_test.go]:
```
msg-att         = "(" (msg-att-dynamic / msg-att-static)
                   *(SP (msg-att-dynamic / msg-att-static)) ")"
msg-att-dynamic = "FLAGS" SP "(" [flag-fetch *(SP flag-fetch)] ")"
                    ; MAY change for a message
msg-att-static  = "ENVELOPE" SP envelope / "INTERNALDATE" SP date-time /
                  "RFC822" [".HEADER" / ".TEXT"] SP nstring /
                  "RFC822.SIZE" SP number /
                  "BODY" ["STRUCTURE"] SP body /
                  "BODY" section ["<" number ">"] SP nstring /
                  "UID" SP uniqueid

flag            = "\Answered" / "\Flagged" / "\Deleted" /
                  "\Seen" / "\Draft" / flag-keyword / flag-extension
flag-extension  = "\" atom
flag-fetch      = flag / "\Recent"
flag-keyword    = atom
```

File: message_test.go [hunk 17]
```diff
@@ -66,11 +66,11 @@ var messageTests = []struct {
...
+			RawString("BODY"), bodyStructureTests[0].fields,
+			RawString("FLAGS"), []interface{}{RawString(SeenFlag), RawString(AnsweredFlag)},
+			RawString("RFC822.SIZE"), RawString("4242"),
+			RawString("UID"), RawString("2424"),
```
Comment (foxcpp) [inline message_test.go]:
```
body-fld-lines  = number
body-fld-octets = number
body-type-msg   = media-message SP body-fields SP envelope
                  SP body SP body-fld-lines
```

File: response_test.go [hunk 18]
```diff
@@ -12,7 +12,7 @@ func TestResp_WriteTo(t *testing.T) {
 	var b bytes.Buffer
 	w := imap.NewWriter(&b)
 
-	resp := imap.NewUntaggedResp([]interface{}{"76", "FETCH", []interface{}{"UID", 783}})
+	resp := imap.NewUntaggedResp([]interface{}{imap.RawString("76"), imap.RawString("FETCH"), []interface{}{imap.RawString("UID"), 783}})
```
Comment (foxcpp) [inline response_test.go]:
```
response-data   = "*" SP (resp-cond-state / resp-cond-bye /
                  mailbox-data / message-data / capability-data) CRLF
message-data    = nz-number SP ("EXPUNGE" / ("FETCH" SP msg-att))
```

File: search_test.go [hunk 19]
```diff
@@ -24,10 +24,10 @@ var searchCriteriaTests = []struct {
 	{
 		expected: `(1:42 UID 743:938 ` +
 			`SINCE "5-Nov-1984" BEFORE "21-Nov-1997" SENTSINCE "5-Nov-1984" SENTBEFORE "21-Nov-1997" ` +
-			`FROM root@protonmail.com BODY "hey there" TEXT DILLE ` +
```
Comment (foxcpp) [inline search_test.go]:
```
search          = "SEARCH" [SP "CHARSET" SP astring] 1*(SP search-key)
search-key      = "ALL" / "ANSWERED" / "BCC" SP astring /
                  "BEFORE" SP date / "BODY" SP astring /
                  "CC" SP astring / "DELETED" / "FLAGGED" /
                  "FROM" SP astring / "KEYWORD" SP flag-keyword /
                  "NEW" / "OLD" / "ON" SP date / "RECENT" / "SEEN" /
                  "SINCE" SP date / "SUBJECT" SP astring /
                  "TEXT" SP astring / "TO" SP astring /
                  "UNANSWERED" / "UNDELETED" / "UNFLAGGED" /
                  "UNKEYWORD" SP flag-keyword / "UNSEEN" /
                    ; Above this line were in [IMAP2]
                  "DRAFT" / "HEADER" SP header-fld-name SP astring /
                  "LARGER" SP number / "NOT" SP search-key /
                  "OR" SP search-key SP search-key /
                  "SENTBEFORE" SP date / "SENTON" SP date /
                  "SENTSINCE" SP date / "SMALLER" SP number /
                  "UID" SP sequence-set / "UNDRAFT" / sequence-set /
                  "(" search-key *(SP search-key) ")"
header-fld-name = astring
```

File: server/cmd_auth_test.go [hunk 20]
```diff
@@ -387,7 +387,7 @@ func TestList_Subscribed(t *testing.T) {
 	io.WriteString(c, "a001 LSUB \"\" *\r\n")
 
 	scanner.Scan()
-	if scanner.Text() != "* LSUB () \"/\" INBOX" {
+	if scanner.Text() != "* LSUB () \"/\" \"INBOX\"" {
```
Comment (foxcpp) [inline server/cmd_auth_test.go]:
```
mailbox         = "INBOX" / astring
mailbox-data    =  "FLAGS" SP flag-list / "LIST" SP mailbox-list /
                   "LSUB" SP mailbox-list / "SEARCH" *(SP nz-number) /
                   "STATUS" SP mailbox SP "(" [status-att-list] ")" /
                   number SP "EXISTS" / number SP "RECENT"
mailbox-list    = "(" [mbx-list-flags] ")" SP
                   (DQUOTE QUOTED-CHAR DQUOTE / nil) SP mailbox
```

File: server/cmd_selected_test.go [hunk 21]
```diff
@@ -424,7 +424,7 @@ func TestCopy(t *testing.T) {
 
 	io.WriteString(c, "a001 STATUS CopyDest (MESSAGES)\r\n")
 	scanner.Scan()
-	if !strings.HasPrefix(scanner.Text(), "* STATUS CopyDest (MESSAGES 1)") {
+	if !strings.HasPrefix(scanner.Text(), "* STATUS \"CopyDest\" (MESSAGES 1)") {
```
Comment (foxcpp) [inline server/cmd_selected_test.go]:
```

mailbox         = "INBOX" / astring
mailbox-data    =  "FLAGS" SP flag-list / "LIST" SP mailbox-list /
                   "LSUB" SP mailbox-list / "SEARCH" *(SP nz-number) /
                   "STATUS" SP mailbox SP "(" [status-att-list] ")" /
                   number SP "EXISTS" / number SP "RECENT"
```

File: client/cmd_auth_test.go (hunk 2 above)
Comment (emersion) [reply client/cmd_auth_test.go]: Hmm, so actually `INBOX` is a little annoying: I've seen e-mail servers and clients that don't like it when it's quoted. I guess we'll need to special-case this one (maybe with a `FormatMailbox` function in go-imap?).

Comment (foxcpp) [reply client/cmd_auth_test.go]: Done, see cc4b00e.

File: server/cmd_auth_test.go [hunk 22]
```diff
@@ -289,7 +289,7 @@ func TestList(t *testing.T) {
 	io.WriteString(c, "a001 LIST \"\" *\r\n")
 
 	scanner.Scan()
-	if scanner.Text() != "* LIST () \"/\" INBOX" {
+	if scanner.Text() != "* LIST () \"/\" \"INBOX\"" {
```
Comment (emersion) [inline server/cmd_auth_test.go]: Missing a `FormatMailboxName` somewhere?

File: server/cmd_auth_test.go [hunk 23]
```diff
@@ -436,7 +436,7 @@ func TestStatus(t *testing.T) {
 
 	scanner.Scan()
 	line := scanner.Text()
-	if !strings.HasPrefix(line, "* STATUS INBOX (") {
+	if !strings.HasPrefix(line, "* STATUS \"INBOX\" (") {
```
Comment (emersion) [inline server/cmd_auth_test.go]: Same?

File: status.go [hunk 24]
```diff
@@ -39,7 +39,7 @@ const (
 	StatusRespBye StatusRespType = "BYE"
 )
 
-type StatusRespCode string
+type StatusRespCode RawString
```
Comment (emersion) [inline status.go]: Hmm, `StatusRespCode` can't be used directly, since it's a new type (not `RawString`)

Comment (foxcpp) [reply status.go]: Oh, right. I don't even remember why I changed it.

File: server/cmd_auth_test.go (hunk 22 above)
Comment (foxcpp) [reply server/cmd_auth_test.go]: Fixed.
