### PR TITLE
fix: empty envelope address fields

### LINKED ISSUE #361: Envelope sender should be `nil` instead of `()`
As stated in [this issue](https://github.com/jonhoo/rust-imap/issues/166), the envelope parsing does not adhere to the spec.

It might be an issue i should fill in `go-imap` but i'm not sure about that, so i post it here in the meantime.

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #361.

### CODE REVIEW

File: message.go [hunk 1]
```diff
@@ -707,7 +707,12 @@ func ParseAddressList(fields []interface{}) (addrs []*Address) {
 
 // Format an address list to fields.
 func FormatAddressList(addrs []*Address) (fields []interface{}) {
-	fields = make([]interface{}, len(addrs))
+	addr_len := len(addrs)
```
Comment (emersion) [inline message.go:710]: Style: Go uses `camelCase`. But I don't think it's worth it to define a variable here, we can just inline `len(addrs)` at both sites.

File: message_test.go [hunk 2]
```diff
@@ -391,6 +391,15 @@ func TestAddressList(t *testing.T) {
 	}
 }
 
+func TestEmptyAddressList(t *testing.T) {
+    addrs := make([]*Address, 0)
```
Comment (emersion) [inline message_test.go:395]: Style: we use tabs.

You can make sure the style is okay by running `go fmt ./...`.

Apart from this LGTM!

Comment (kyazdani42) [reply message_test.go]: (forgot to run gofmt). I'll try to build hydroxide against this to see if the issue is properly fixed

**Comment by emersion** [comment]
You can run hydroxide with this by using a local copy of go-imap by changing hydroxide's go.mod:

```
replace github.com/emersion/go-imap => /path/to/patched/go-imap
```

**Comment by kyazdani42** [comment]
Ok well the issue is still happening. I need to dig deeper:
as go nil value for arrays is `[](nil)` and not `nil`, when formatting, it returns `[]` instead of `nil`.

**Comment by emersion** [comment]
Maybe making `FormatAddressList` return `interface{}` could help? That way it would return a nil interface, rather than an empty slice.

**Comment by kyazdani42** [comment]
You were right.
I'll update the tests and it should be all good !

File: write.go [hunk 3]
```diff
@@ -195,7 +195,11 @@ func (w *Writer) writeField(field interface{}) error {
 	case Literal:
 		return w.writeLiteral(field)
 	case []interface{}:
-		return w.writeList(field)
+		if len(field) == 0 {
```
Comment (emersion) [inline write.go:198]: This is incorrect, an empty slice should be formatted as `()`

Comment (kyazdani42) [reply write.go:198]: that's what i thought, but it breaks the tests otherwise.

Comment (kyazdani42) [reply write.go:198]: `expected, _ := formatFields(test.fields)` will format incorrectly

Comment (emersion) [reply write.go:198]: Not changing something shouldn't break tests that pass.

Comment (kyazdani42) [reply write.go:198]: except that those tests are failing because now that the envelope can have nil fields, the addresses change so `TestMessage_Format` and `TestEnveloppe_Format` will break.

Comment (kyazdani42) [reply write.go:198]: Should i create a new writer for the Envelope then ?

Comment (kyazdani42) [reply write.go:198]: hum my bad, i should just change the test data ...

Comment (emersion) [reply write.go:198]: Can't we just fix `envelopeTests`? Basically replace `[]interface{}{}` with `nil`.

Comment (kyazdani42) [reply write.go]: should be all good now :)
